```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```

Bring in CASFRI and NBR harvest data

```{r}
# CAS-FRI
load("0_data/manual/spatial/cas_cov.rData")

# NBR
load("0_data/manual/spatial/nbr_fin_all_2.rDATA")

#Remove unnecessary fields
NBR<-nbr_fin_all_2[c(2:4, 63, 65, 67, 73, 75, 85, 95)]%>%
  # mutate(RdNBR=totDistb_mean_in/abs(preDistMean_mean_in)^.5)%>%
  rename(c(dNBR=totDistb_mean_in, RdNBR=relDistbVal_mean_in, dNBR_recovery=totRegen_mean_in, NBR_survey=surveyNBR_mean_in, NBR_preDist=preDistMean_mean_in, yod=yod_mean_in, eocYr=eocYr_mean_in, survey_year=srvy_yr))%>%
  mutate(dNBR_perc=dNBR/NBR_preDist)


# distance to polygon edge
load("0_data/manual/spatial/bd_xy_edge.rData")
load("0_data/manual/spatial/bd_xy_cas.rData")
```



Join
```{r eval=FALSE}
spatial_cov<-left_join(data.frame(bd_xy_cas[1:2]), cas_cov,  by='cas_id')%>%
  left_join(., NBR, by=c('SS','cas_id'))%>%
  left_join(.,bd_xy_edge, c("SS", "cas_id"))

save(spatial_cov, file="0_data/manual/spatial/spatial_cov.rData")
```

